{
  tester.reset();
  try {
    assertUpdate(sql);
    fail("expected exception");
  }
 catch (  RuntimeException e) {
    assertEquals(tester.getCalledName(),name);
    assertEquals(tester.getCalledArguments(),list());
    assertEquals(e.getMessage(),message);
  }
}
