{
  tester.reset();
  try {
    assertUpdate(sql);
    fail("expected exception");
  }
 catch (  RuntimeException e) {
    assertFalse(tester.wasCalled());
    assertEquals(e.getMessage(),message);
  }
}
