{
  try {
    evaluateInvalid(projection);
    fail("Expected to throw an NUMERIC_VALUE_OUT_OF_RANGE exception with message " + message);
  }
 catch (  PrestoException e) {
    assertEquals(e.getErrorCode(),NUMERIC_VALUE_OUT_OF_RANGE.toErrorCode());
    assertEquals(e.getMessage(),message);
  }
}
