{
  try {
    limiter.checkAssignFrom(node);
    fail("expected exception");
  }
 catch (  PrestoException e) {
    assertEquals(e.getErrorCode(),expected.toErrorCode());
  }
}
