{
  try {
    return future.get();
  }
 catch (  InterruptedException e) {
    Thread.currentThread().interrupt();
    throw new RuntimeException("Interrupted while waiting for future",e);
  }
catch (  ExecutionException e) {
    Throwable cause=e.getCause();
    if (cause instanceof Error) {
      throw new ExecutionError((Error)cause);
    }
    throw new UncheckedExecutionException(cause);
  }
}
