{
  tester.recordCalled("exception");
  throw new PrestoException(INVALID_PROCEDURE_ARGUMENT,"test exception from procedure");
}
